APP_NAME=approveDoc
PROJECT_CODE=approvedoc
TEMPLATE_VERSION_AT_CREATION=1.1.2
COMPANY_NAME=ionetiq
DOWNLOADS_DIR=C:\Users\mikeb\My Drive\Downloads
WORKING_DIR=C:\inetpub\wwwroot\approveDoc
GITHUB_REPO_URL=https://github.com/ionetiqdev/approveDoc.git
SUPABASE_PROJECT_NAME=approvedoc
