# cache-bust.ps1
#
# Called by deploy.bat (Step 4). Takes the published timestamp as a
# parameter rather than having it interpolated into a quoted string
# by cmd.exe - this avoids the nested-quote escaping that made the
# old inline `powershell -Command "..."` version fragile (it could
# fail silently: powershell.exe itself would still exit 0, so
# deploy.bat's `if errorlevel 1` check never caught it, even though
# version.js was never actually being rewritten).
#
# Usage: powershell -NoProfile -ExecutionPolicy Bypass -File cache-bust.ps1 -PublishedTimestamp "27/06/2026 17:55"

param(
  [Parameter(Mandatory = $true)]
  [string]$PublishedTimestamp
)

$ErrorActionPreference = 'Stop'

# Regenerate the cache-busting query string across every .html file.
$cb = -join ((48..57) + (97..122) | Get-Random -Count 8 | ForEach-Object { [char]$_ })
Get-ChildItem -Recurse -Filter *.html | ForEach-Object {
  (Get-Content $_.FullName -Raw) -replace '\?r=[a-zA-Z0-9_]+', ('?r=' + $cb) |
    Set-Content -NoNewline $_.FullName
}

# Write a fresh version.js carrying this build's published timestamp.
$versionJs = @"
/* Auto-generated by deploy.bat - do not edit */
const APP_PUBLISHED = '$PublishedTimestamp';
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('[data-published]').forEach(function(el) {
    el.textContent = 'Published ' + APP_PUBLISHED;
  });
});
"@

Set-Content -Path 'assets\js\version.js' -Value $versionJs -NoNewline

Write-Host "version.js written with APP_PUBLISHED = '$PublishedTimestamp'"
